from django.core.management.base import BaseCommand
from regions.models import Region

REGIONS = [
    # (name, parent_name)
    ("Bakı", None),
    ("Sumqayıt", None),
    ("Gəncə", None),
    ("Abşeron", "Bakı"),
    ("Binəqədi", "Bakı"),
    ("Nərimanov", "Bakı"),
    ("Nəsimi", "Bakı"),
    ("Sabunçu", "Bakı"),
    ("Suraxanı", "Bakı"),
    ("Xətai", "Bakı"),
    ("Yasamal", "Bakı"),
    ("Qaradağ", "Bakı"),
    ("Səbail", "Bakı"),
    ("Xəzər", "Bakı"),
    ("Pirallahı", "Bakı"),
    ("Şəki", None),
    ("Mingəçevir", None),
    ("Şirvan", None),
    ("Naftalan", None),
    ("Şuşa", None),
    ("Ağdam", None),
    ("Ağcabədi", None),
    ("Ağdaş", None),
    ("Ağstafa", None),
    ("Ağsu", None),
    ("Astara", None),
    ("Balakən", None),
    ("Bərdə", None),
    ("Beyləqan", None),
    ("Biləsuvar", None),
    ("Cəbrayıl", None),
    ("Cəlilabad", None),
    ("Daşkəsən", None),
    ("Füzuli", None),
    ("Gədəbəy", None),
    ("Goranboy", None),
    ("Göyçay", None),
    ("Göygöl", None),
    ("Hacıqabul", None),
    ("İmişli", None),
    ("İsmayıllı", None),
    ("Kəlbəcər", None),
    ("Kürdəmir", None),
    ("Qax", None),
    ("Qazax", None),
    ("Qəbələ", None),
    ("Qobustan", None),
    ("Quba", None),
    ("Qubadlı", None),
    ("Qusar", None),
    ("Laçın", None),
    ("Lənkəran", None),
    ("Lerik", None),
    ("Masallı", None),
    ("Neftçala", None),
    ("Oğuz", None),
    ("Ordubad", None),
    ("Qəbələ", None),
    ("Saatlı", None),
    ("Sabirabad", None),
    ("Salyan", None),
    ("Samux", None),
    ("Siyəzən", None),
    ("Şabran", None),
    ("Şamaxı", None),
    ("Şəmkir", None),
    ("Şərur", None),
    ("Tərtər", None),
    ("Tovuz", None),
    ("Ucar", None),
    ("Xaçmaz", None),
    ("Xızı", None),
    ("Xocalı", None),
    ("Xocavənd", None),
    ("Yardımlı", None),
    ("Yevlax", None),
    ("Zaqatala", None),
    ("Zəngilan", None),
    ("Zərdab", None),
]

class Command(BaseCommand):
    help = "Azərbaycanın bütün regionlarını bazaya əlavə edir."

    def handle(self, *args, **options):
        name_to_obj = {}
        for name, parent_name in REGIONS:
            parent = name_to_obj.get(parent_name) if parent_name else None
            obj, created = Region.objects.get_or_create(name=name, parent=parent)
            name_to_obj[name] = obj
        self.stdout.write(self.style.SUCCESS("Bütün regionlar əlavə olundu!"))
