# Generated by Django 5.2.4 on 2025-08-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True, verbose_name='referal kodu'),
        ),
    ]
