# Generated by Django 5.2.4 on 2025-08-13 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default="123456789asdfghj", editable=False, max_length=16, unique=True, verbose_name='referal kodu'),
            preserve_default=False,
        ),
    ]
