# Generated by Django 5.2.4 on 2025-08-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(editable=False, max_length=32, unique=True, verbose_name='referal kodu'),
        ),
    ]
