# Generated by Django 5.2.4 on 2025-08-11 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subregions', to='regions.region', verbose_name='Ana Region')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regionlar',
                'indexes': [models.Index(fields=['name'], name='region_name_idx')],
            },
        ),
    ]
