name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script_stop: true
          script: |
            set -ex

            PROJECT_PATH="${{ secrets.PROJECT_PATH }}"
            REPO_URL="${{ secrets.REPO_URL }}"
            COMPOSE_FILE_NAME="docker-compose.yml"

            cd "$PROJECT_PATH"

            # Repo yoxdursa klonla, varsa main-ə reset et
            if [ ! -d .git ]; then
              echo "Git repo tapılmadı, klonlayıram..."
              git clone "$REPO_URL"
            else
              echo "Repo tapıldı, origin/main-ə sinxronizə edirəm..."
              git fetch --all
              git reset --hard origin/main
            fi

            # entrypoint.sh permission
            chmod +x ./src/entrypoint.sh

            # Ya da sadəcə: git pull origin main
            git pull origin main

            # Servisləri yenilə
            docker compose down
            docker compose -f docker-compose-prod.yml up -d --build --remove-orphans