name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script_stop: true
          script: |
            set -e

            PROJECT_PATH="${{ secrets.PROJECT_PATH }}"
            REPO_URL="${{ secrets.REPO_URL }}"
            BRANCH="main"
            COMPOSE_FILE="docker-compose-prod.yml"

            echo "PROJECT_PATH: $PROJECT_PATH"
            echo "REPO_URL: $REPO_URL"
            
            cd "$PROJECT_PATH"
            
            echo "Checking .git directory:"
            if [ -d .git ]; then
              echo ".git var → pull"
              git fetch origin "$BRANCH"
              git checkout "$BRANCH"
              git pull --ff-only origin "$BRANCH"
            else
              echo ".git yoxdur → clone"
              git clone --depth=1 --branch "$BRANCH" "$REPO_URL" .
            fi

            # entrypoint.sh permission
            chmod +x ./src/entrypoint.sh

            docker compose -f "$COMPOSE_FILE" up -d --build --remove-orphans